### PR TITLE
Vector fill and more

### PR DESCRIPTION
**Pull request by CandyFace**
### What's new
Reworked vector fill, vector selection, refactoring and added draft documentation for VectorImage class. Fixed points sticking to each other on overlap. Curves can now be painted separately, and the width of the curve can be changed as well.

### How it works now:
vector fill1

The first time you draw a curve and fill it, both the area and the curve will be filled with the same color. Afterwards you can choose to select the curve or the area or both to fill. You select a curve or area by using the move tool.  

For now filling a vector stroke will not respect color boundaries but merely fill the path of the curve.

### What's removed
+ curve visualization on hover.

### CODE REVIEW

**Comment by Jose-Moreno** [comment]
@CandyFace Awesome!

**Comment by chchwy** [comment]
Cool work @CandyFace! 
I just returned today from a 2-week holiday break, I'll review it asap.
And I think we can prepare for the 0.6 release.

**Comment by CandyFace** [comment]
@chchwy Welcome back :D
That sounds good, though it would be nice if we could get it tested some more. @Jose-Moreno would you mind testing this build:
https://drive.google.com/file/d/0B3Jkb3m7pLp4VzJWb1RVY2ZHX2c/view?usp=sharing
While bugs has been fixed here and there, you focus on how vector filling works now, and the way you fill a curve and area and such.

**Comment by Jose-Moreno** [comment]
@CandyFace Sure thing, i'll test it during the day and let you guys know. On the other hand I reported a bug earlier, that although is not app-breaking @chchwy should take a look at it since it involves the camera layer https://github.com/pencil2d/pencil/issues/765

**Pull request merged**
