### PR TITLE
Refactor title save indicator and add file icon to main window title

### PR DESCRIPTION
**Pull request by scribblemaniac**
Instead of manually prepending the asterisk to the window title to indicate file changes, this lets QT handle it. On Window and Linux I don't think there will be any noticeable difference from this change, but on Mac, the close button will change when the current file has unsaved changes. I have also added a file icon to the window title (again probably mac only), which will be greyed out slightly when there are unsaved changes, as is typical of Mac applications.

### CODE REVIEW

**Comment by chchwy** [comment]
Thanks @scribblemaniac, I agreed that let Qt handle the save status is better.
And as I checked, close button & file icon changes are not available on Windows, so we might need to find a way to let Win/Linux users know the file has been saved or not (like an asterisk).

**Comment by scribblemaniac** [comment]
> And as I checked, close button & file icon changes are not available on Windows, so we might need to find a way to let Win/Linux users know the file has been saved or not (like an asterisk).

That stuff is indeed just for mac. On windows/linux, qt should add the asterisk automatically. That is based off of the docs, I haven't tested it yet, but this code should theoretically handle this already.

**Comment by chchwy** [comment]
Could you give a link for the documentation? I didn't see the asterisk.
I'll be happy if we don't need to deal with it.

**Comment by scribblemaniac** [comment]
Oops, seems like I need to read it more carefully. I pushed a new commit that should hopefully make it show up now. The documentation is here:
https://doc.qt.io/qt-5/qwidget.html#windowModified-prop

**Comment by chchwy** [comment]
Did a quick test, once the asterisk shows, the asterisk will never disappear even after saving file.

**Comment by scribblemaniac** [comment]
> Did a quick test, once the asterisk shows, the asterisk will never disappear even after saving file.

Hmmm, okay I'll look into it again

**Comment by scribblemaniac** [comment]
What a pain, sorry for this. The asterisk should show *and* disappear now.

**Comment by chchwy** [comment]
Now it works very well. Thanks @scribblemaniac

**Pull request merged**
