### PR TITLE
Update Toolbar Icons

### PR DESCRIPTION
**Pull request by scribblemaniac**
Now that we've got v0.6.0 out of the way, we can use the new icon set made by @CandyFace in #667.

Related issues: #603, #550, and #801.

### CODE REVIEW

**Comment by J5lx** [comment]
Besides, while not related to this PR, the tip of the pencil seems to vanish on the dark background of my theme:

screenshot from 2017-12-02 13-41-57

@CandyFace

**Comment by CandyFace** [comment]
Looking good @scribblemaniac As far as I can see though, this will require manual tweaking. The SVG conversion to SVG tiny 1.2 has made some crude changes here and there. For a small icon, 32x, 64x, it might work but if we are to have bigger icons, the files will have to be tweaked so they look as close to the original SVG files.

@J5lx That's going to be difficult to fix, given that it's an issue caused by the color choice of your theme. I'll see what I can without making too drastic changes.

**Comment by scribblemaniac** [comment]
@J5lx Fixed. Mac really hates files with the same case.

For reference purposes, I had to convert to SVG Tiny 1.2 because otherwise they look like this:
screen shot 2017-12-02 at 9 56 38 am

**Comment by chchwy** [comment]
@scribblemaniac Are you going to update the icons in Tools menu as well?

**Comment by CandyFace** [comment]
ehm.. whoops O_o Why did it even let me commit directly to your branch. Oh well XD @scribblemaniac  I've committed some changes to your branch, adding the icons to tool menu and tweaked some icons as I mentioned

**Comment by J5lx** [comment]
Thanks, it’s a little better now:
screenshot from 2017-12-04 20-10-09
Still not optimal, but at least it doesn’t feel completely invisible now. Let’s keep it like that for now and maybe we can talk about theme-centered icon improvements some more in #550 eventually.

Also, good thing you added them to the menu, I had already forgotten completely about that myself :p

Other than that, I noticed that I now get a bunch of these in the terminal:

    qt.svg: link _Image4 hasn't been detected!
    qt.svg: link _Image4 hasn't been detected!
    …
    qt.svg: link _Image4 hasn't been detected!
    qt.svg: link _Image4 hasn't been detected!
    …
    qt.svg: link _Image4 hasn't been detected!
    …

I have absolutely no idea what that means and the interface seems fine but it doesn’t sound positive :p Do you two have any idea about this?

**Comment by CandyFace** [comment]
I found some image4 reference in one of the svg files, which I've now removed. I didn't notice any changes in the svg itself, so I think it's fine. The warnings are gone now at least.

**Comment by J5lx** [comment]
Actually I wasn’t even referring to theme-specific icons but yes, that would also be an interesting thing of course :). Most headache-free route might be to have some generic monochromatic icon sets (light and dark) available so there’s less potential colour conflicts to worry about.

**Pull request merged**
