### PR TITLE
#1193 Changing feather range to 1-99

### LINKED ISSUE #1193: High feathering values do not allow pixel application on canvas
### Issue Summary

Any feathering value above 96 (tested with Qt by modifying ui files) will clamp the feather and not draw any pixels at all. This affects particularly the Brush Tool as it is the only active tool that paints with variable feathering but this is a global issue, so the Pencil tool, the Smudge tool or any other tool that would be set to sue feathering would suffer from this issue.

### Expected Results

I mentioned before a value fo 200 might be good, but what I meant was that a value that amtched the maximum SIZE value, would work, however it seems the calculations say otherwise.

On Discord it was suggested to clamp the feathering values from 0 to 100, but the maximum feathering value should never stop the user from painting, at most it will give a very faint and smoothed out paint feel.

### Steps to reproduce

1. Open Pencil2D
2. Select the brush tool and move the slider to the right most edge. The input box will say 80, but this is another bug reported here: #1194
3. Try to draw anything.
4. Move the slider to the left little by little until you can draw and compare.

### System Information
+ Pencil2D Version:
Version: 0.6.3
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

### PR DESCRIPTION
**Pull request by davidlamhauge**
This closes #1193 and #1194 .
Since the value indicates the alpha-value of the feathering, 100 = invisible. For this reason it could be argued that we should have 99 as maximum. Right now it is set to 100.

### CODE REVIEW

**Comment by CandyFace** [comment]
I'd say that it should be 1-99, the brush shouldn't be able to go invisible since the user could consider that a bug.

**Comment by Jose-Moreno** [comment]
I agree with CandyFace, and it's actually written in the expected results for 1193. Feathering should never impede the user from painting because it's only meant to lighten the amount of color that is applied on the canvas so strokes look softer.

**Comment by davidlamhauge** [comment]
I agree, but as I remember the discussion we had, it was undecided, so I had to choose something. I'll change it later today.

**Comment by davidlamhauge** [comment]
Maximum feather set to 99.

**Pull request merged**
