### PR TITLE
Disable onion skin while playing

### PR DESCRIPTION
**Pull request by CandyFace**
#378 onion skin should be disabled on playback.

mission accomplished 🤘

### CODE REVIEW

**Comment by Jose-Moreno** [comment]
@CandyFace ouch I didnt see this before. Is it possible to make this toggable? I normally do use onion skin while doing playback to check the spacing between the drawings at full speed.

**Comment by CandyFace** [comment]
@Jose-Moreno I've made it optional now ;)
screen shot 2018-04-23 at 18 17 53

**Comment by Jose-Moreno** [comment]
@CandyFace Aww man, thanks! I know most people get annoyed by seeing the onion skin on playback, but even pro software do have the ability to toggle the onion skin on playback since sometimes even if you "flip" through the frames by hand, it's different when you see the gaps between the drawings at playback speed.

Normally what I had to do was just to turn off the onion skin and play a few times, then turn it on again and play the animation a few more :laughing: 

Again thanks a lot!

**Comment by chchwy** [comment]
Reviewing

**Comment by chchwy** [comment]
Generally the PR is good, appreciate your work @CandyFace!

I found that Pixmap cache is broken at the moment when reviewing the code. it means every time we play the animation it repaint everything even it can be cached. It's not related to this PR though. Just keep a note.

**Pull request merged**
