### PR TITLE
Toolbars

### PR DESCRIPTION
**Pull request by chchwy**
An initial PR of adding Toolbars. The toolbars are in a basic usable level that having only essential/frequently used items.
I want to bring it up early for your attention and discussion. More features/PRs will come later on.

Currently, there are 3 toolbar sections:

1. Main toolbar: New, Open, Save, Cut, Copy, Paste, Undo, Redo
2. View toolbar: Zoom in/out, Reset view, Flip horizontal/Vertical
3. Overlay toolbar: Show/hide Grid

You can show/hide each of the toolbars under `Windows` menu.

Implementing toolbars have two goals:

1. Addressing #1047 & #1455 for touch screen users to easily access menu features (e.g., Undo/Redo) without a keyboard.
2. Addressing #1417, to efficiently utilize UI space for low res display users. It's meant to replace DisplayOptions with View/Overlay Toolbars. (not done yet, will come later on)

toolbars

BTW, toolbars can be snap to any side of the main window, not only the top area.
snap-left

### CODE REVIEW

**Comment by chchwy** [comment]
And note: some of the menu items don't have icons. We probably need to make them.

**Comment by Jose-Moreno** [comment]
@chchwy Nice work. A quick note on  #1455 that issue meant to be requesting an empty, fully customizable widget (I called it a toolbar but it could be a panel) that people can modify according to their preference and allow them to place any action available on Pencil2D menus or other panels as a quick access. In that sense this PR should not be linked to close the aforementioned issue.

From the presented view toolbar are the zoom icons meant to be clicked repeatedly to increase / decrease the zoom % factor? Or are they meant to be held down to drag over the surface? I'm asking because having these buttons would probably be duplicating the _zoom slider_ that will be implemented by #1442 If anything perhaps that zoom slider widget could be moved to your toolbar instead after both PR's are merged.

Regarding the view toolbar itself, I understand you separated this one to contain the actions that affect the view itself such as zoom, mirror, etc. I just made a request in #1469 to separate the reset transforms. These individual buttons could also be added to this toolbar in that case.

I think it's great that the overlays will also have the grid toggle and adding the layout composition guides will make sense there. For the vector related buttons _show outlines_ and _show invisible_ I'd probably keep them in the **overlays toolbar** since just by the current division we could consider the overlays to affect how the user sees or filters the content without necessarily changing the view (unlike the usual transforms).

If I can think of anything else i'll comment again.

**Comment by Jose-Moreno** [comment]
> And note: some of the menu items don't have icons. We probably need to make them.

For this along the overall interface icons there was some progress discussed in #1356 and the PR is #1361 however it's true that there are plenty of missing icons for the menu actions

**Comment by chchwy** [comment]
1. Currently it's not customizable. It's always possible to implement the ability of toolbar customization in the future.
2. The items on the toolbar are not decided yet. I will be happy to remove the zoom things if the status bar zoom slider code is merged.
3. All the items on the toolbar are buttons at the moment, no drag, just click.
4. I am going to add the rest of "DisplayOptions" to toolbars. 
5. Probably `show outlines` and `show invisible` could be in a separate "Vector" toolbar?

**Review by MrStevns — APPROVED** [review]
Changes looks good to me, I say we merge this one, it's been sitting there for far too long.

I found conflict markers in the latest commit, so I fixed that and will merge the PR now.
There are users who have been waiting for this for a long time, good job Matt 👍

**Pull request merged**
