### PR TITLE
Add doxygen support

### LINKED ISSUE #716: Introduce API documentation
Since our current codebase is rather scarcely documented, it seems that all agree that we should introduce some actual, structured internal API documentation. As of now, Doxygen seems to be the means of choice as documentation generator, and @scribblemaniac is working on a configuration for Pencil on [his add-doxygen branch](https://github.com/scribblemaniac/pencil/tree/add-doxygen). Until it is done, we should discuss remaining issues such as automated deployment of generated documentation here.

References: #540 (particularly https://github.com/pencil2d/pencil/issues/540#issuecomment-255045764)

Related: #683 (regarding formatting of documentation comments)

### PR DESCRIPTION
**Pull request by scribblemaniac**
Adds support for generating documentation with doxygen and automatic deployment to github pages with travis.

@chchwy In order to set this up properly, you need to generate a github personal access token and run the command `travis encrypt --add -repo pencil2d/pencil GH_REPO_TOKEN=<access_token>`

Closes #716
Related #540, #683

### CODE REVIEW

**Comment by chchwy** [comment]
Thanks @scribblemaniac.
Had a quick glance this PR will upload the Doxygen docs into gh-pages branch, right?
Just wonder, Is it possible to upload the doc to `pencil2d.github.io` repo?

**Comment by scribblemaniac** [comment]
> Had a quick glance this PR will upload the Doxygen docs into gh-pages branch, right?

Correct.

> Just wonder, Is it possible to upload the doc to pencil2d.github.io repo?

It is possible. You would change the GH_REPO_REF env variable in the .travis.yml and remove the "-b gh-pages" from line 51 of documentation-deploy.sh.

**Comment by scribblemaniac** [comment]
Oh and if you wanted to put it somewhere other than the docs folder, you would need to modify lines 66, 67, and 86 of documentation-deploy.sh accordingly.

**Comment by chchwy** [comment]
Thanks @scribblemaniac, It works file.

<https://pencil2d.github.io/pencil-docs/docs/>

**Pull request merged**
