### PR TITLE
Implement separate reset pan and rotation options

### PR DESCRIPTION
**Pull request by J5lx**
This PR implements separate actions for resetting pan (i. e. centring the view) and resetting rotation, as requested in #1469. I did not implement an option to reset zoom since we already have one (View→Zoom→100%). As suggested in the original issue, the default shortcuts are based on the “Reset All” shortcut (Ctrl+H) with different modifiers. I didn’t add any visual toggles because I think those would work best on a toolbar, which is about to be added by #1468. Since the reset zoom option already had a menu entry in the zoom submenu, I did not create a new submenu, but rather grouped the “reset rotation” action with the existing rotation actions and the “center view” action with the “reset all” action. But of course we can still choose to go with a little redundancy and add the extra menu instead if that turns out to be better.

### CODE REVIEW

**Review by CandyFace — APPROVED** [review]
LGTM!

**Comment by J5lx** [comment]
Builds for testing: [Windows x86_64](https://drive.google.com/file/d/1ppCb75dn4OMJ0sfLikt0mWzFoQgk9xd9/view?usp=sharing), [Windows x86](https://drive.google.com/file/d/1CJVRmY9SUANuL2uP2mpaAbB4hBe4o49Z/view?usp=sharing), [macOS](https://drive.google.com/file/d/1uoLRWVCTrsZ492FmtTG5ZG75vQjs4rRl/view?usp=sharing), [Linux](https://drive.google.com/file/d/1Sv3vv67tE1q-K3tZ5WjOv7_4b9Necckp/view?usp=sharing)

**Comment by Jose-Moreno** [comment]
@J5lx Alright I tested the build you provided. Thank you for that. I think both Center View and Reset Rotation settings work well. My only question is why a separate Reset Zoom was not included, considering it was part of the issue requirements? 

While the general **Reset** does take care of the zoom reset, it also defaults all the other properties. While drawing there are certain times where you want to reset only the zoom but not the tilt or the position of the canvas, particularly if you're drawing details and you want to zoom out quickly to gauge the whole picture and then zoom in again to continue drawing.

That'd be my only observation to an otherwise good job 👍

**Comment by J5lx** [comment]
Maybe if it isn’t that intuitive we could also rename it to “100% (Reset)” or something like that. Does that sound like a good idea?

**Comment by Jose-Moreno** [comment]
@J5lx Apologies didn't see your last comment. I think it's alright to leave it as it is for now and probe the community to see if there are better ways to organize these options with workflow efficiency and UX in mind.

**Pull request merged**
