### PR TITLE
Updated shortcuts

### LINKED ISSUE #1444: Expose pending old and new functionality in the shortcut list
### Issue Summary

****
|File>Import|File>Export|Edit|Animation|Tools|Layer|Windows|
|---|---|---|---|---|---|---|
|Image Predefined Set|Animated GIF|PegBar Alignment|Range|Reset to Default|Change Line (Pixel) Color|Lock Windows|
|Movie Import|   |   |   |   |   |   |
|Animated GIF|   |   |   |   |   |   |
|Layers from PCLX|   |   |   |   |   |   |
|Movie Audio|   |   |   |   |   |   |
|Append Palette|   |   |   |   |   |   |
|Replace Palette|   |   |   |   |   |   |

_**Note**_ `CmdPreview ALT + P` What is this? It doesn't seem to work, does this exist in preparation for the preview feature that was discussed before?

### System Information
+ Pencil2D Version:
Version: 0.6.5

commit: 50a0c7c318f38988af85d34e955a5a78d3953474
date: 2020-08-01_01:32:15

Operating System: Windows 10 (10.0)
CPU Architecture: x86_64
Qt Version: 5.12.9

### PR DESCRIPTION
**Pull request by HeCorr**
Somewhat related to #1016 / Fixes #1444.

This PR removes the following unused shortcuts:
- `Export Sound` `(Ctrl+I)`
- `Preview` `(Alt+P)`

..and adds the following missing shortcuts:
- `Export Animated GIF` `(Ctrl+G)`
- `Toggle Center Overlay`
- `Toggle Thirds Overlay`
- `Toggle Golden Ratio Overlay`
- `Toggle Safe Areas Overlay`
- `Toggle One Point Perspective Overlay`
- `Toggle Two Point Perspective Overlay`
- `Toggle Three Point Perspective Overlay`
- `Import Image Predefined Set`
- `Import Movie Video`
- `Import Movie Audio`
- `Import Animated Image`
- `Import Layers from project file`
- `Import Palette (Append)`
- `Import Palette (Replace)`
- `Toggle Range Playback`
- `Peg bar Alignment`
- `Lock Windows`
- `Reset all tools to default`
- `Change Line Color (Current keyframe)`
- `Change Line Color (All keyframes on layer)`
- `Selection: Reposition Frames`
- `Change Layer / Keyframe Opacity`

Please let me know if I've missed any!

### CODE REVIEW

**Comment by HeCorr** [comment]
The `View > Preview (Alt + P)` action/menu item/shortcut [seems to be unused](https://github.com/pencil2d/pencil/issues/1444#issuecomment-2244216282) as well. Should I go ahead and remove it?

If so, should I also remove the (seemingly abandoned) [preview.cpp](https://github.com/pencil2d/pencil/blob/eba8d6db44a31ce9574bb76076b90bbbe64b81c9/app/src/preview.cpp) file?

**Comment by MrStevns** [comment]
Nice job HeCorr!

Yes please remove the preview file, given that no one has touched it in forever, I think we should remove it.

**Comment by chchwy** [comment]
> Nice job HeCorr!
> 
> I'd recon that we remove the preview file for now, since it's been lying there for a long time and never gotten fully implemented but maybe @chchwy disagree?

It's totally fine to remove it for now. It should be added back once the feature is fully functional.

**Comment by HeCorr** [comment]
Preview feature and it's shortcuts removed!

I found some more missing shortcuts to add.

**Review by MrStevns — APPROVED** [review]
Changes looks good to me.

> Should it be Frames or Keyframes?

We're not quite consistent regarding this, for now I'd say use the menu names as those might have translations already.

**Pull request merged**
