### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by JonasThomas**
This fixes Black become while on the color pallet  when File->New is chosen.
However, it appears the nothing is drawing on the scribble area.

### CODE REVIEW

**Comment by JonasThomas** [comment]
basically file->new , load files,  needed to have init called after the object was set in the editor so the colorpallete freshes correctly.

**Comment by tasaif** [comment]
Tested this PR
current master branch behavior:
- black brush strokes work
- new file
(color switches to white)
- change color to black
- strokes no longer work

your master branch:
- black brush strokes don't work from the onset

your bugFix branch:
- black brush strokes work
- new file
(color does not switch to white)
- strokes still don't work

**Comment by tasaif** [comment]
Fixed the color thing in #405

**Comment by JonasThomas** [comment]
Yah... that camera switching thing messed me up too. ;)  While the Black is White is fixed.  I noticed that some of the custom colors in the colorpalette many be turning black.   Are you seeing that as well?

**Comment by tasaif** [comment]
I haven't noticed that yet

**Comment by JonasThomas** [comment]
It seems like the Black is white issue has been by tasaif and merged into the master so it seems this is no longer required.

**Pull request closed without merging**
