### PR TITLE
moved mEditor->setObject( object ) to correct position

### PR DESCRIPTION
**Pull request by JonasThomas**
Fixed my boo boo.  Happy new year.

### CODE REVIEW

**Comment by chchwy** [comment]
@JonasThomas, I have to say thanks for your contribution first, but I'm afraid that I'm going to revert this commit. 

Switch the order of `setObject()` and `init()` may lead other problems, we must ensure every Manager (ex. ViewManager or ColorManager) is created and init before `setObject()`, otherwise the managers will not got notified through `onObjectLoaded()`.

@tasaif has fixed the color problem in fc872de580 properly.

Hope you can understand :)

**Comment by JonasThomas** [comment]
@chchwy   No prolblem the important thing is that it gets fixed overall, but the explanation is appreciated.
(I thought moving the setobject() befor the init() sort of stunk also  but it seemed to solve the problem in my head.  Ie it reloaded the colorPallete.
The fix that @tasaif does assumes that the first color in the colorPallette will always be be black.(This totally works for me btw)    
If someone has an itch to customize the colorPalette where the first color is not black, down the road that could be an issue.  I wondering if there should be a code comment for future develepors.

**Comment by feeef** [comment]
@JonasThomas In the case of a custom color palette when opening an existing project, the palette is reloaded after the object is set through setObject() 

https://github.com/pencil2d/pencil/blob/master/app/mainwindow2.cpp#L494

**Comment by JonasThomas** [comment]
@feeef Yep.... that's the rabbit hole I went down.. ;)   I was trying to rap my head around what was going on with setObject but there's so much going on it was hard for me to understand what was happening stepping into the code.

**Comment by feeef** [comment]
I fixed this bug : https://github.com/feeef/pencil/commit/e5af91f2b21fe1f01dbd3b4ab454a875a39662ff

**Pull request merged**
