### PR TITLE
add a frame pool cache option

### PR DESCRIPTION
**Pull request by 0x72D0**
PR for #1076

### CODE REVIEW

**Comment by 0x72D0** [comment]
yes from what I seen the frame pool cache is set at the beginning of the program and I don't really know how to change it immediately after changing it in the preference... That why I only put a little warning to restart the program each time the value is changed

**Comment by chchwy** [comment]
Okay no worries. I will take care of the rest of the parts.

**Comment by 0x72D0** [comment]
ok, thanks!

**Comment by chchwy** [comment]
Merged. Thank you @0x72D0

**Pull request merged**
