### PR TITLE
proper view transformation for vector layer (only cursor)

### LINKED ISSUE #737: circle cursor doesn't adapt to correct QTransform in Vector
### --Issue Summary--
This is related to  #725 
I forgot that the two layer types are using different coordinate systems. Bitmap is on relative coordinates with (0,0) being in the center of the canvas, while on Vector, (0,0) is located in the top left corner... aside from that the coordinates are also reversed. This has not been noticed until now because internally QCursor would just adapt to whatever coordinate system you threw at it.
### --Actual Results
Circle cursor is placed incorrectly in the top left corner, when the mouse cursor is placed in the middle of the canvas. coordinates are also reversed. 

### --Expected Results--

Circle cursor should follow and adapt to the position of the mouse cursor coordinates.

### --System Information--
commit: 8f2057fdeda9c8e56ce16f1ee15674630d782f2d
date: 2017-08-12_12:02:51

### PR DESCRIPTION
**Pull request by CandyFace**
fixes #737

### CODE REVIEW

**Comment by CandyFace** [comment]
Discovered a problem while zooming, don't merge.

**Comment by CandyFace** [comment]
Now you may merge.

**Comment by chchwy** [comment]
Cool @CandyFace

**Comment by Kaikogf** [comment]
It is working fine here

**Pull request merged**
