### PR TITLE
Fix appveyor.

### PR DESCRIPTION
**Pull request by CandyFace**
After much trial and error, I finally figured a combination of quotes and backslashes that works on windows.

### CODE REVIEW

**Comment by J5lx** [comment]
Well, *compiles* on Windows, not *works* on Windows… Everything else would have been too good to be true, I guess.

The about dialog without a git timestamp

(Note that while the screenshot was taken with Wine I’ve also confirmed the missing timestamp in Windows 10)

At this point I haven’t looked into the cause, though. FWIW, the [port](https://github.com/J5lx/pencil/tree/meson) to the [meson build system](http://mesonbuild.org/) I originally mentioned in https://github.com/pencil2d/pencil/issues/530#issuecomment-293109549 works splendidly, see the 2017-04-18 builds at <https://drive.google.com/open?id=0ByqfJUKSPYQtZHBzTjllVUpreUU> (the 2017-04-19 ones are based on this PR, so they do not work).

**Comment by CandyFace** [comment]
Hahahaha pff.. it really was too good to be true. I can't test whether it shows the text or not since I don't have a windows nearby with VS.

**Comment by J5lx** [comment]
For testing you can use [Wine](https://winehq.org/) or a VM with a [Windows Insider build](https://insider.windows.com/), both are free (at least as in free beer). That’s what I use when I desperately need to hack on Windose stuff. You can also use #649 to extract your own AppVeyor builds.

**Comment by CandyFace** [comment]
I would have done if I had enough space left. I have Wine though but not enough space to get  

I've found an elegant solution though, using stringification.

**Comment by J5lx** [comment]
Can confirm it works. Great Job!

**Pull request merged**
