### PR TITLE
Refactor .travis.yml

### PR DESCRIPTION
**Pull request by J5lx**
Basically just got rid of a few hardcoded directories. Can never hurt.

### CODE REVIEW

**Comment by J5lx** [comment]
Also added a fix for running the tests from the wrong directory.

**Comment by CandyFace** [comment]
@J5lx i've made a PR on your repo to fix some of the problems on mac :)

**Comment by J5lx** [comment]
Merged. Thanks!

**Comment by chchwy** [comment]
Thanks guys.

**Pull request merged**
