### PR TITLE
Updated build instructions for linux

### PR DESCRIPTION
**Pull request by vrockz747**
Added instructions for ```broken packages``` error while installing using ```apt-get```

### CODE REVIEW

**Comment by vrockz747** [comment]
Please review this PR @J5lx

**Comment by Jose-Moreno** [comment]
@vrockz747 I've updated the automation and labels for this PR. We'll now have to wait for a reviewer to merge this. Thanks again for your contribution.

**Review by scribblemaniac — COMMENTED** [review]
I don't think this additional note should be included in our documentation. Quite frankly, these broken packages are likely an issue specific to your system and are not something that I would expected to happen commonly when using apt normally. Likely an installation of one of these packages or their dependencies failed, either during running this command for the first time, or potentially from a previous package installation attempt. For issues specific to one system, or that are not directly related to the setup/build process, it is best if we defer support to external resources such as StackOverflow.

**Comment by vrockz747** [comment]
Makes sense @scribblemaniac, I will then close this PR

**Comment by vrockz747** [comment]
Makes sense @scribblemaniac, should i just add this [reference] (https://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages) instead?

**Comment by chchwy** [comment]
Please add it as a reference, please. :)

**Comment by scribblemaniac** [comment]
We have discussed these changes further and have decided that while providing additional guidance to help users compile our program is welcome, we believe in this particular case that the issue you've encountered is too specific to warrant any inclusion in our documentation at this time. We can always revisit this later if we find other people experiencing similar issues.

Speaking personally now as a person who has used a Debian-based distro as his primary OS for many years now, you will encounter many issues like this where you just have to look them the error on StackOverflow or elsewhere online. A broken package could be caused by many things, none of which we have any control over. It could have been an issue with the package of one of the dependencies of this program, or it could have been any error during a previous package installation/update. This is not something I would expect to happen often when following the instructions outlined in our Linux compilation guide.

Sorry for taking so long to deal with this relatively minor PR. Things sometimes move very slowly around here. Thank you for your contribution.

**Pull request closed without merging**
