### PR TITLE
Start on bitmap layer

### PR DESCRIPTION
**Pull request by tasaif**
When creating a new document, bitmap layer should be selected by default
#374 #397 #409

### CODE REVIEW

**Comment by JonasThomas** [comment]
Cool.. Look forward to giving this a try tonight after work.  (Are you on the forum?)

**Comment by feeef** [comment]
Thanks @tasaif ! :)
As we are now a few contributors to this code, we should talk to organise ourselves. If you are not in the forum please join us : http://www.pencil2d.org/?post_type=forum

**Comment by JonasThomas** [comment]
I was hoping to give this a try, but it hasn't been merged yet.  I suppose I can pull it from your repo.

**Comment by tasaif** [comment]
Sorry

**Comment by JonasThomas** [comment]
Not a big deal.  It is sort of a gotcha bug though.

**Comment by JonasThomas** [comment]
Sweet...   This is one of those things that you don't even notice when your using the app, but sure is annoying when it doesn't work..  Tested all the permutation, where I noticed it... All better as near as I can tell.   Thanks,

**Pull request merged**
