### PR TITLE
Make it pass desktop-file-validate on Ubuntu trusty

### PR DESCRIPTION
**Pull request by probonopd**
Reference:
https://github.com/AppImage/appimage.github.io/pull/194

### CODE REVIEW

**Comment by J5lx** [comment]
How does the changed version affect newer DEs/WMs? If it makes them ignore the Keywords key or something, I’m in favour of keeping version 1.1 in the file and adjusting it on-the-fly during the AppImage build process (or maybe offering a pre-made alternative desktop file for AppImages). (Especially since the desktop entry is also installed during `make install` and thus not exclusive to AppImages.) Thoughts, @scribblemaniac, @probonopd?

**Comment by probonopd** [comment]
Since AppImages are generally supposed to also run on the oldest still-supported LTS distributions, the most recent version of the XDG desktop file spec you can use at this time is 1.0. This does not affect the functionality in any way on newer DEs/WMs, which are fully backward compatible.

**Comment by scribblemaniac** [comment]
If this was all that needed to be changed, I might be in favor of it, however I know that the old desktop-file-validate is not going to pass this just by changing the version number. The "Keyword" key is invalid for 1.0 desktop files and would have to be removed completely, obviously breaking the keyword feature used for things like searches. So, I suppose it depends on exactly what happens when 14.04 users try to use our 1.1 desktop file. If it works fine and throws some warning, then leave it as is, if it crashes the program then maybe change it.

**Comment by chchwy** [comment]
@J5lx how will you do the on-the-fly desktop file adjusting?

**Comment by J5lx** [comment]
Using a `sed` line or two in .travis.yml :) Come to think about it, maybe we could also abstract the AppImage build process into its own shell script considering #811.

**Comment by J5lx** [comment]
Alright then, I’ll come up with a proper solution asap.

**Comment by J5lx** [comment]
@probonopd An alternative solution to this problem was recently merged in #871. Could you verify whether it is sufficient?

**Comment by probonopd** [comment]
> Could you verify whether it is sufficient?

I can do that as soon there is a release available that contains this fix.

**Comment by J5lx** [comment]
@probonopd We just released 0.6.1, containing the fix: https://github.com/pencil2d/pencil/releases/download/v0.6.1/pencil2d-linux-amd64-0.6.1.AppImage

**Comment by probonopd** [comment]
Thank you.

**Pull request closed without merging**
