### PR TITLE
make travis ready for google drive integration

### PR DESCRIPTION
**Pull request by CandyFace**
I've tested everything aside from the upload process to google drive, since the private key is not set up for my account. if @chchwy has made the preparations mentioned in #617, my assumption is that it'll work when the PR has been merged.

The changes to the Travis file should in the end upload two files to google drive, one for linux and another for mac. The zip files are named like this: pencil2d-os-date where os is linux or mac and date is year-month-day

As i've previously said, Travis-CI doesn't support Windows yet, so at some point i'll see if I can get it setup on Appveyor too but that's a task for another day.

### CODE REVIEW

**Comment by chchwy** [comment]
Thanks @CandyFace, testing right now.

**Comment by CandyFace** [comment]
Hmm... console spits out 
"The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys."

I wonder if it's going to work... did you setup the key correctly?

**Comment by chchwy** [comment]
Looking at the issue, probably I didn't escape all special characters properly.

**Comment by CandyFace** [comment]
Baah.. I too found a typo in the script.. fixing.. get ready for PR

**Pull request merged**
