### PR TITLE
#691 shortcuts are no longer hardcoded

### PR DESCRIPTION
**Pull request by CandyFace**

### CODE REVIEW

**Comment by chchwy** [comment]
#691

**Comment by chchwy** [comment]
The shortcuts don't update until a restart is because tooltips need to be updated manually lol.  The function  `MainWindow2::setupKeyboardShortcuts()` will be triggered after shortcut changes.

However, I'm thinking that removing the shortcut from tool tips. Users could still know the shortcut from the main menu, then we don't have to worry about it. Thoughts?

**Comment by Jose-Moreno** [comment]
@chchwy I don't think it's a big deal if the default shortcuts are not reflected on the tooltips after changing them. However it would be worse to lack those entirely. From a user stand point it's better to have the tooltips pointing at the default shortcut layout even if you change them than not having them at all. 

When you as a user manage to change the shortcuts it's because you have a certain familiarity with the software, but if you don't know which ones are default then it's difficult to learn the tools. However if this is too much of a hassle then we have to make it extra clear that the shortcut layout is on the preferences.

People could look at the shortcut list on the preferences, but let's face it, a rough 90% of our user base does not do that. I've had to point out a lot of times, options that are specifically located in the preferences simply because people do not look for them.  They just open Pencil2D and expect it to work "out of the box".

**Comment by chchwy** [comment]
I think you're right @Jose-Moreno 
Let's keep them and i'm going to merge this pr.

**Comment by CandyFace** [comment]
I think the shortcuts are good to have when you hover over the tools, it's much easier than opening preferences and checking out the shortcut list and it is also a somewhat common design choice being used by various applications too, thus I think it should stay. 

I have been looking into the first special cases but haven't been able to find a solution so far. It is indeed trickier than it first seems, initially I thought that adding "None" to empty keys in kb.ini would work, but it doesn't accept strings so that wasn't possible. Then I tried to check whether the QKeySequence would be empty an then replace it's content, but that no good either as it's just a reference to the shortcut key (which doesn't exist) 

The second special case shouldn't be that hard, it's just a matter of calling the toolbox  update when you've hit assign from the shortcut list (or so I imagine) that should be enough to trigger an shortcut update.

**Comment by chchwy** [comment]
User could get shortcut information from main menu, not necessary to open preference window 


But I agree that it's good to show shortcuts in tool tips.

**Pull request merged**
