### PR TITLE
Implementation of operations widget

### PR DESCRIPTION
**Pull request by nickbetsworth**
Addresses #1047

Apologies it took so long, only managed to start working on it yesterday evening.

Let me know if you'd like you change any design decisions.

### CODE REVIEW

**Comment by nickbetsworth** [comment]
Does anyone know why the CI build has failed with the following error?

```
if [ "$TRAVIS_BRANCH" != "release" ]; then bash $TRAVIS_BUILD_DIR/util/checkchanges.sh; fi
fatal: Invalid symmetric difference expression origin/master...ecc645d39769f73c06aaf7d4a7fb5293b0c91171
The command "if [ "$TRAVIS_BRANCH" != "release" ]; then bash $TRAVIS_BUILD_DIR/util/checkchanges.sh; fi" failed and exited with 128 during .
```

**Comment by davidlamhauge** [comment]
@nickbetsworth I don't know why Travis failed, but I know it does it all the time, and I'm always told to not worry. So - you shouldn't worry...

**Comment by CandyFace** [comment]
Alrighy here's a few comments. 
My observations are that the UI widget is taking up a considerable amount of space, considering the space the buttons actually needs, this seems too much.
I also think that the icons could be a tad smaller, 16x16 or 18x18 maybe.. not quite the size of a toolbox icon. 
image

The redo icon should only be enabled when it's actually usable, same with undo.

**Comment by Jose-Moreno** [comment]
@CandyFace Two questions:
1) Would it be possible to take the icons, modify them and then commit them to this PR?
2) Can we make the panel fluid enough to work in a single horizontal & vertical line as well as a "grid" layout? This would be similar to how the toolbox widget works when the size is constrained to a single column, though it doesn't work for a horizontal single row.

**Comment by CandyFace** [comment]
@Jose-Moreno 
1. Yes it's possible, you should be able to push directly to his repo, granted that you have the appropriate permissions.
2. That depends... it makes use of FlowLayout so it should already behave the same, with the same limitations.

I don't think they should have configurable size if that's what you mean, but a bit smaller would be preferred. They're imo. not as important as the toolbox therefore they should not require the same sizes.

**Comment by chchwy** [comment]
Hey @nickbetsworth. Thanks for your contribution & sorry for the late reply.

I had a look at this PR. Is there any reason you pick QDockWidget rather than QToolbar? Just ondering because this widget is very similar to a toolbar.

**Comment by chchwy** [comment]
@nickbetsworth unfortunately I am closing this PR as similar features can be made by the `QToolbar` and I think it's the better way to do this. I appreciate your time in helping pencil2d. Please feel free to send more PR if you have any ideas. Thanks.

**Pull request closed without merging**
